apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
spec:
  project: kargo-gen-demo
  syncPolicy:
    automated: {}
  source:
    repoURL: https://github.com/dhpup/kargo-appset-gen.git
    targetRevision: main
    path: apps
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: argocd
