apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: dev
      - stage: test
      - stage: preview
      - stage: prod-euwest
      - stage: prod-uswest
  template:
    metadata:
      name: guestbook-{{stage}}
      annotations:
        kargo.akuity.io/authorized-stage: guestbook:{{stage}}
    spec:
      project: kargo-demo
      source:
        repoURL: https://github.com/blakepettersson/kargoring.git
        targetRevision: stage/{{stage}}
        path: guestbook/stages/{{stage}}
      destination:
        name: blake
        namespace: guestbook-{{stage}}
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
