apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - name: oci-guestbook
            repoUrl: oci://registry-1.docker.io/blaaake
            chart: helm-guestbook
            image: ghcr.io/dhpup/guestbook
  template:
    metadata:
      name: 'kargo-{{.name}}'
    spec:
      project: kargo-gen-demo
      source:
        repoURL: https://github.com/dhpup/kargo-project-gen.git
        path: .
        helm:
          valuesObject:
            nameOverride: '{{.name}}'
            warehouse:
              subscriptions:
                - chart:
                    repoURL: '{{.repoUrl}}/{{.chart}}'
                    semverConstraint: '*'
                - image:
                    repoURL: '{{.image}}'
                    semverConstraint: '*'
            stages:
              - name: dev
                annotations:
                  kargo.akuity.io/color: purple
                subscriptions:
                  warehouse: '{{.name}}'
                promotionMechanisms:
                  argoCDAppUpdates:
                    - appName: '{{.name}}-dev'
                      sourceUpdates:
                        - repoURL: '{{.repoUrl}}'
                          chart: '{{.chart}}'
                          helm:
                            images:
                              - image: '{{.image}}'
                                key: image.tag
                                value: Tag # Update Application to reference the new image version
                          updateTargetRevision: true # Update Application to reference the new chart version
      destination:
        name: kargo1
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true
