apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kargo-demo
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Kargo Example Project
  sourceRepos:
    - '*'
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
      namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: false